apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-api
  template:
    metadata:
      labels:
        app: student-api
    spec:
      containers:
        - name: student-api
          image: puneetbt11/student-api:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
