---
- name: Configure EC2 Docker Server
  hosts: webservers
  become: true

  tasks:

    - name: Update apt package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Make sure Docker is running
      service:
        name: docker
        state: started
        enabled: true
